### ISSUE TITLE
Plugin non-functioning in ST2

### ISSUE THREAD

**Issue by revdave33** [phyllisstein/HipsterIpsum#1]
I'm not sure when, but HipsterIpsum stopped working.

This is the error message in the console

Reloading plugin .../.config/sublime-text-2/Packages/Hipster Ipsum/hipsteripsum.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./hipsteripsum.py", line 9, in <module>
    import requests
  File "./requests/**init**.py", line 52, in <module>
    from . import utils
  File "./requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "./requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "./requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "./requests/packages/urllib3/**init**.py", line 16, in <module>
    from .connectionpool import (
  File "./requests/packages/urllib3/connectionpool.py", line 44, in <module>
    from .request import RequestMethods
  File "./requests/packages/urllib3/request.py", line 12, in <module>
    from .filepost import encode_multipart_formdata
  File "./requests/packages/urllib3/filepost.py", line 11, in <module>
    from io import BytesIO
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio

**Comment by phyllisstein** [comment]
Thanks for the heads-up! I've just pushed a fix that should take care of the problem. I made a boo-boo importing Requests, but I think I've bandaged it. Let me know how it works for you!

**Comment by revdave33** [comment]
Unfortunately, this didn't seem to work. I am getting the same traceback. version 2013.04.06.01.14.40

**Comment by phyllisstein** [comment]
Hm, curious! I think this may have to do with your Python installation, since ST2 uses your native Python and the requests module doesn't bundle the thing you're missing, namely something from `io`. You might try updating your `io` module and seeing if that solves the problem.

**Comment by twolfson** [comment]
+1 I am running into the same error on ST2 Version 2.0.1, Build 2217; Hipster Ipsum version 2013.04.06.01.14.40; Python 2.7.3.

I am guessing it is something with the requests version you downloaded.

For the record, here is my error:

```
Reloading plugin /home/todd/.config/sublime-text-2/Packages/Hipster Ipsum/hipsteripsum.py
Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./hipsteripsum.py", line 9, in <module>
    import requests
  File "./requests/__init__.py", line 52, in <module>
    from . import utils
  File "./requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "./requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "./requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "./requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "./requests/packages/urllib3/connectionpool.py", line 44, in <module>
    from .request import RequestMethods
  File "./requests/packages/urllib3/request.py", line 12, in <module>
    from .filepost import encode_multipart_formdata
  File "./requests/packages/urllib3/filepost.py", line 11, in <module>
    from io import BytesIO
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio
```

**Comment by phyllisstein** [comment]
Hi, Todd, and thanks for corroborating the problem. I take it you're running Ubuntu, but can you tell me how you installed your Python and if it's at all possible that the `io` module is incomplete? As I said, this is not a module that comes bundled with Requests, so it's assumed to be platform-agnostic. I will, however, also take a look at updating the Requests bundle and seeing if that helps---thanks for the idea.

**Comment by twolfson** [comment]
I am actually running Linux Mint 14. Python either came pre-installed on the machine or it was installed via `sudo apt-get`, I cannot really remember. it seems that `BytesIO` does exist on my machine which is peculiar

``` shell
$ python
Python 2.7.3 (default, Sep 26 2012, 21:51:14) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from io import BytesIO
>>> BytesIO
<type '_io.BytesIO'>
```

Ah, I apologize for being mistaken regarding Requests coming bundled. For what it's worth, I tried out other versions of Requests when reporting this, 0.14.2 and 1.2.3, but I still received the same error. Although, I was second guessing if I had properly replaced it (`rm -r`, `cp (git dir)`).

I will take a look again now.

**Comment by twolfson** [comment]
Sublime Text 2 is definitely running a bundled version of Python. I just got this from its terminal

``` shell
>>> from io import BytesIO
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".\io.py", line 63, in <module>
ImportError: No module named _fileio
```

**Comment by twolfson** [comment]
Looks like it is `urllib2` or bust =/

**Comment by twolfson** [comment]
Alright, done. Submitting a patch shortly.
