### ISSUE TITLE
Broken in ST3

### ISSUE THREAD

**Issue by pepelsbey** [phyllisstein/HipsterIpsum#4]
When I’m running it both from `Cmd Shift P` menu or using `Ctrl Alt H` shortcut I’m getting the following error:

```
[Hipster Ipsum: Exception: 'MockRequest' object has no attribute 'origin_req_host']
Exception in thread Thread-29:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "hipsteripsum in /Users/pepelsbey/Library/Application Support/Sublime Text 3/Installed Packages/Hipster Ipsum.sublime-package", line 138, in run
UnboundLocalError: local variable 'r' referenced before assignment
```

ST3 is the latest dev 3062, nothing special regarding my OS X: 10.9.4, system Python 2.7.5.

**Comment by andytruett** [comment]
Same error, ST3 3062, Win7.

**Comment by andrewmartin** [comment]
Seeing this as well in OSX.

**Comment by parzival418** [comment]
Just got this as well.  Any fixes out there?

**Comment by andytruett** [comment]
Any updates for this great plugin?

**Comment by andytruett** [comment]
@michaelsharpe @pepelsbey @andrewmartin

Try [my fork →](https://github.com/andytruett/HipsterIpsum/commit/f11cf0552f7006834bfb263f0ad319db4f1493b8) for a fix.

**Comment by bfricka** [comment]
@andytruett namaste!
